from __future__ import annotations

import argparse
import json
import math
import subprocess
from pathlib import Path

from .flux_spectra import cached_flux_histograms
from .nuhepmc_rootracker import ParticleRecord, RooTrackerEvent, write_rootracker
from .provenance import checksum
from .validation import validate_nonempty


NEUTRINO_PDGS = {12, 14, 16}
MODE_BY_NEUT_CODE = {
    1: ("CC", "QES"),
    51: ("NC", "QES"),
    11: ("CC", "RES"),
    31: ("NC", "RES"),
    26: ("CC", "DIS"),
    46: ("NC", "DIS"),
    16: ("CC", "COH"),
    36: ("NC", "COH"),
    # NuWro's converter falls back to 100 for its enabled CC hyperon channel.
    100: ("CC", "HYP"),
}


def parser() -> argparse.ArgumentParser:
    command = argparse.ArgumentParser(
        prog="python -m dlpgen_opt.nuwro_cli",
        description="Run NuWro from cached canonical dk2nu spectra.",
    )
    command.add_argument("--flux-manifest", type=Path, required=True)
    command.add_argument("--flux-spectra-manifest", type=Path, required=True)
    command.add_argument("--work-dir", type=Path, required=True)
    command.add_argument("--native-output", type=Path, required=True)
    command.add_argument("--params-output", type=Path, required=True)
    command.add_argument("--output", type=Path, required=True)
    command.add_argument("--metadata-output", type=Path, required=True)
    command.add_argument("--events", type=int, required=True)
    command.add_argument("--test-events", type=int, required=True)
    command.add_argument("--seed", type=int, required=True)
    command.add_argument("--executable", default="nuwro")
    command.add_argument("--converter", default="nuwro2rootracker")
    command.add_argument("--target-a", type=int, required=True)
    command.add_argument("--target-z", type=int, required=True)
    command.add_argument("--energy-min-gev", type=float, required=True)
    command.add_argument("--energy-max-gev", type=float, required=True)
    command.add_argument("--energy-bins", type=int, required=True)
    command.add_argument("--processes", nargs="+", choices=("cc", "nc"), required=True)
    command.add_argument("--vertex-cm", type=float, nargs=3, required=True)
    return command


def _spectrum_values(path: Path) -> list[float]:
    values: list[float] = []
    with path.open(encoding="utf-8") as stream:
        for line_number, line in enumerate(stream, start=1):
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            fields = stripped.split()
            if len(fields) != 2:
                raise RuntimeError(f"invalid spectrum row {path}:{line_number}")
            value = float(fields[1])
            if not math.isfinite(value) or value < 0:
                raise RuntimeError(f"invalid spectrum weight {path}:{line_number}")
            values.append(value)
    if not values or sum(values) <= 0:
        raise RuntimeError(f"empty flux spectrum: {path}")
    return values


def render_params(
    histograms: dict[int, dict[str, object]],
    *,
    events: int,
    test_events: int,
    seed: int,
    target_a: int,
    target_z: int,
    processes: list[str],
    energy_min_gev: float,
    energy_max_gev: float,
    energy_bins: int,
) -> str:
    if events <= 0 or test_events <= 0:
        raise ValueError("NuWro event counts must be positive")
    if target_z < 0 or target_z > target_a:
        raise ValueError("invalid NuWro target nucleus")
    beam_lines = []
    for pdg, record in sorted(histograms.items()):
        path = Path(record["path"])
        values = _spectrum_values(path)
        if len(values) != energy_bins:
            raise RuntimeError(
                f"NuWro spectrum {path} has {len(values)} bins, expected {energy_bins}"
            )
        integral = float(record["integral_per_cm2"])
        if not math.isfinite(integral) or integral <= 0:
            raise RuntimeError(f"invalid flux integral for PDG {pdg}")
        profile = " ".join(
            [
                f"{energy_min_gev * 1000:.12g}",
                f"{energy_max_gev * 1000:.12g}",
                *(f"{value:.16g}" for value in values),
            ]
        )
        beam_lines.append(f"{pdg} {integral:.16g} % {profile}")
    if not beam_lines:
        raise RuntimeError("NuWro flux projection contains no flavors")

    cc = int("cc" in processes)
    nc = int("nc" in processes)
    lines = [
        "# Generated by dlpgen-opt; NuWro energies are expressed in MeV.",
        f"random_seed = {seed}",
        f"number_of_events = {events}",
        f"number_of_test_events = {test_events}",
        "save_test_events = 0",
        "beam_type = 1",
        "beam_particle = 14",
        "beam_direction = 0 0 1",
        f"nucleus_p = {target_z}",
        f"nucleus_n = {target_a - target_z}",
        "target_type = 0",
        "FSI_on = 1",
        f"dyn_qel_cc = {cc}",
        f"dyn_qel_nc = {nc}",
        f"dyn_res_cc = {cc}",
        f"dyn_res_nc = {nc}",
        f"dyn_dis_cc = {cc}",
        f"dyn_dis_nc = {nc}",
        f"dyn_coh_cc = {cc}",
        f"dyn_coh_nc = {nc}",
        f"dyn_mec_cc = {cc}",
        f"dyn_mec_nc = {nc}",
        f"dyn_hyp_cc = {cc}",
        "dyn_lep = 0",
        "beam_content = " + beam_lines[0],
        *("beam_content += " + line for line in beam_lines[1:]),
        "",
    ]
    return "\n".join(lines)


def _reaction(neut_code: int, pdgs: list[int], statuses: list[int]) -> tuple[str, str]:
    if neut_code in MODE_BY_NEUT_CODE:
        return MODE_BY_NEUT_CODE[neut_code]
    if neut_code == 2:
        incoming = next(
            (pdg for pdg, status in zip(pdgs, statuses) if status == 0 and abs(pdg) in NEUTRINO_PDGS),
            0,
        )
        charged_lepton = abs(incoming) - 1
        current = "CC" if any(
            status == 1 and abs(pdg) == charged_lepton
            for pdg, status in zip(pdgs, statuses)
        ) else "NC"
        return current, "MEC"
    return "Unknown", "Unknown"


def normalize_rootracker(
    native_rootracker: Path,
    output: Path,
    *,
    vertex_cm: tuple[float, float, float],
) -> int:
    try:
        import ROOT  # type: ignore
    except ImportError as error:
        raise RuntimeError("ROOT is required to normalize NuWro output") from error
    source = ROOT.TFile.Open(str(native_rootracker), "READ")
    tree = source.Get("nRooTracker") if source else None
    if not source or source.IsZombie() or not tree:
        raise RuntimeError(f"invalid native NuWro RooTracker file: {native_rootracker}")
    events: list[RooTrackerEvent] = []
    try:
        for index, entry in enumerate(tree):
            count = int(entry.StdHepN)
            pdgs = [int(entry.StdHepPdg[i]) for i in range(count)]
            statuses = [int(entry.StdHepStatus[i]) for i in range(count)]
            particles = tuple(
                ParticleRecord(
                    pdg=pdgs[i],
                    status=statuses[i],
                    momentum_gev=tuple(
                        float(entry.StdHepP4[4 * i + axis]) for axis in range(4)
                    ),
                )
                for i in range(count)
                if statuses[i] in (0, 1)
            )
            incoming = next(
                (pdg for pdg, status in zip(pdgs, statuses) if status == 0 and abs(pdg) in NEUTRINO_PDGS),
                0,
            )
            target = next(
                (pdg for pdg, status in zip(pdgs, statuses) if status == 0 and abs(pdg) >= 1_000_000_000),
                -1,
            )
            neut_code = int(str(entry.EvtCode.GetString()))
            current, mode = _reaction(neut_code, pdgs, statuses)
            reaction = (
                f"nu:{incoming};tgt:{target};N:-1;"
                f"proc:Weak[{current}],{mode};generator_process:{neut_code};"
            )
            x, y, z = vertex_cm
            events.append(
                RooTrackerEvent(
                    event_number=index,
                    process_id=neut_code,
                    reaction=reaction,
                    vertex_m=(x / 100.0, y / 100.0, z / 100.0, 0.0),
                    particles=particles,
                    cross_section_1e38_cm2=float(entry.EvtXSec),
                    weight=1.0,
                    probability=1.0,
                )
            )
    finally:
        source.Close()
    write_rootracker(events, output)
    return len(events)


def run(args: argparse.Namespace) -> dict[str, object]:
    args.work_dir.mkdir(parents=True, exist_ok=True)
    histograms = cached_flux_histograms(
        args.flux_spectra_manifest,
        args.flux_manifest,
        energy_min=args.energy_min_gev,
        energy_max=args.energy_max_gev,
        bins=args.energy_bins,
    )
    params = render_params(
        histograms,
        events=args.events,
        test_events=args.test_events,
        seed=args.seed,
        target_a=args.target_a,
        target_z=args.target_z,
        processes=args.processes,
        energy_min_gev=args.energy_min_gev,
        energy_max_gev=args.energy_max_gev,
        energy_bins=args.energy_bins,
    )
    args.params_output.parent.mkdir(parents=True, exist_ok=True)
    args.params_output.write_text(params, encoding="utf-8")
    args.native_output.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            args.executable,
            "-i",
            str(args.params_output),
            "-o",
            str(args.native_output),
        ],
        cwd=args.work_dir,
        check=True,
    )
    validate_nonempty(args.native_output)
    intermediate = args.work_dir / "nuwro-native-rootracker.root"
    subprocess.run(
        [args.converter, str(args.native_output), str(intermediate)],
        cwd=args.work_dir,
        check=True,
    )
    validate_nonempty(intermediate)
    count = normalize_rootracker(
        intermediate,
        args.output,
        vertex_cm=tuple(args.vertex_cm),
    )
    intermediate.unlink()
    if count != args.events:
        raise RuntimeError(f"NuWro produced {count} events, expected {args.events}")
    metadata: dict[str, object] = {
        "schema_version": 1,
        "format": "dlpgen-opt-nuwro-rootracker",
        "events": count,
        "seed": args.seed,
        "test_events": args.test_events,
        "target": {"a": args.target_a, "z": args.target_z},
        "processes": args.processes,
        "canonical_manifest_sha256": checksum(args.flux_manifest),
        "spectra_manifest_sha256": checksum(args.flux_spectra_manifest),
        "params_sha256": checksum(args.params_output),
        "native_sha256": checksum(args.native_output),
        "output_sha256": checksum(args.output),
        "executables": {
            "generator": args.executable,
            "converter": args.converter,
        },
    }
    args.metadata_output.parent.mkdir(parents=True, exist_ok=True)
    args.metadata_output.write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return metadata


def main() -> None:
    args = parser().parse_args()
    run(args)


if __name__ == "__main__":
    main()
