from __future__ import annotations

import os
import re
import shlex
import subprocess
from pathlib import Path

import yaml
from pydantic import BaseModel, ConfigDict, Field

from .config import ProductionConfig


class SlurmProfile(BaseModel):
    model_config = ConfigDict(extra="forbid")

    account: str = Field(pattern=r"^[A-Za-z0-9_.:-]+$")
    partition: str = Field(pattern=r"^[A-Za-z0-9_.-]+$")
    cpus_per_task: int = Field(default=1, gt=0)
    mem_per_cpu: str = Field(default="4G", pattern=r"^[0-9]+[KMGTP]?[bB]?$")
    time: str = Field(
        default="02:00:00",
        pattern=r"^(?:[0-9]+-[0-9]{2}:[0-9]{2}:[0-9]{2}|[0-9]+:[0-9]{2}:[0-9]{2})$",
    )
    max_array_size: int = Field(default=99, gt=0)
    bind_paths: list[Path] = Field(default_factory=lambda: [Path("/sdf")])


def load_profile(path: str | Path, name: str) -> SlurmProfile:
    profile_path = Path(path).expanduser().resolve()
    with profile_path.open(encoding="utf-8") as stream:
        raw = yaml.safe_load(stream)
    if not isinstance(raw, dict) or not isinstance(raw.get("profiles"), dict):
        raise ValueError(f"SLURM profile file must contain a profiles mapping: {profile_path}")
    if name not in raw["profiles"]:
        choices = ", ".join(sorted(raw["profiles"]))
        raise ValueError(f"unknown SLURM profile {name!r}; available profiles: {choices}")
    return SlurmProfile.model_validate(raw["profiles"][name])


def _directive(value: str, field: str) -> str:
    if "\n" in value or "\r" in value:
        raise ValueError(f"SLURM {field} must be a single line")
    return value


def render_script(
    config: ProductionConfig,
    profile: SlurmProfile,
    *,
    container: Path,
    first_job: int,
    last_job: int,
    max_concurrent: int | None,
    job_name: str,
    log_dir: Path,
    bind_paths: list[Path],
) -> str:
    array = f"{first_job}-{last_job}"
    task_count = last_job - first_job + 1
    if max_concurrent is not None and max_concurrent < task_count:
        array += f"%{max_concurrent}"
    binds = ",".join(str(path) for path in bind_paths)
    config_path = str(config.config_path)
    command = " ".join(
        shlex.quote(part)
        for part in (
            "singularity",
            "exec",
            "--cleanenv",
            "--env",
            "PYTHONNOUSERSITE=1",
            "--bind",
            binds,
            str(container),
            "/usr/local/bin/dlpgen-opt-entrypoint",
            "run",
            config_path,
            "--job",
            '"${SLURM_ARRAY_TASK_ID}"',
        )
    ).replace("'\"${SLURM_ARRAY_TASK_ID}\"'", '"${SLURM_ARRAY_TASK_ID}"')
    return f"""#!/bin/bash
# Generated by dlpgen-opt from the S3DF CPU profiles in DeepLearnPhysics/spine-prod.
#SBATCH --account={_directive(profile.account, "account")}
#SBATCH --partition={_directive(profile.partition, "partition")}
#SBATCH --ntasks=1
#SBATCH --cpus-per-task={profile.cpus_per_task}
#SBATCH --mem-per-cpu={profile.mem_per_cpu}
#SBATCH --time={profile.time}
#SBATCH --array={array}
#SBATCH --job-name={_directive(job_name, "job name")}
#SBATCH --output={log_dir}/{job_name}_%A_%a.out
#SBATCH --error={log_dir}/{job_name}_%A_%a.err

set -euo pipefail

echo "dlpgen-opt production: {config.production.name}"
echo "SLURM job/task: ${{SLURM_JOB_ID}}/${{SLURM_ARRAY_TASK_ID}}"
echo "Node: ${{SLURM_NODELIST}}"
echo "Started: $(date --iso-8601=seconds)"

test -r {shlex.quote(str(container))}
test -r {shlex.quote(config_path)}

{command}

echo "dlpgen-opt job ${{SLURM_JOB_ID}}/${{SLURM_ARRAY_TASK_ID}} completed successfully"
echo "Completed: $(date --iso-8601=seconds)"
"""


def submit_arrays(
    config: ProductionConfig,
    profile: SlurmProfile,
    *,
    container: str | Path,
    max_concurrent: int | None = None,
    job_name: str | None = None,
    extra_bind_paths: list[str | Path] | None = None,
    dry_run: bool = False,
) -> list[tuple[Path, str | None]]:
    container_path = Path(container).expanduser().resolve()
    if not dry_run and not container_path.is_file():
        raise ValueError(f"Singularity image does not exist: {container_path}")
    if max_concurrent is not None and max_concurrent <= 0:
        raise ValueError("max_concurrent must be positive")

    resolved_name = job_name or config.production.name
    if not re.fullmatch(r"[A-Za-z0-9_.-]+", resolved_name):
        raise ValueError("SLURM job name may contain only letters, numbers, '.', '_' and '-'")

    slurm_dir = config.production.output_dir / "slurm"
    log_dir = slurm_dir / "logs"
    bind_paths = [path.expanduser().resolve() for path in profile.bind_paths]
    bind_paths.extend(Path(path).expanduser().resolve() for path in extra_bind_paths or [])
    bind_paths = list(dict.fromkeys(bind_paths))

    results: list[tuple[Path, str | None]] = []
    dependency: str | None = None
    for first in range(0, config.production.jobs, profile.max_array_size):
        last = min(first + profile.max_array_size, config.production.jobs) - 1
        script = render_script(
            config,
            profile,
            container=container_path,
            first_job=first,
            last_job=last,
            max_concurrent=max_concurrent,
            job_name=resolved_name,
            log_dir=log_dir,
            bind_paths=bind_paths,
        )
        script_path = slurm_dir / f"submit_{first:05d}_{last:05d}.sbatch"
        if dry_run:
            print(f"# {script_path}\n{script}", end="")
            results.append((script_path, None))
            continue

        log_dir.mkdir(parents=True, exist_ok=True)
        script_path.write_text(script, encoding="utf-8")
        try:
            command = ["sbatch", "--parsable"]
            if dependency:
                command.extend(("--dependency", f"afterok:{dependency}"))
            command.append(str(script_path))
            result = subprocess.run(
                command,
                check=True,
                capture_output=True,
                text=True,
            )
        except subprocess.CalledProcessError as error:
            detail = (error.stderr or error.stdout or str(error)).strip()
            raise RuntimeError(f"sbatch failed for {script_path}: {detail}") from error
        job_id = result.stdout.strip().split(";", 1)[0]
        if not job_id:
            raise RuntimeError(f"sbatch returned no job ID for {script_path}")
        print(f"submitted {script_path}: {job_id}")
        results.append((script_path, job_id))
        dependency = job_id
    return results


def default_container() -> str | None:
    return os.environ.get("DLPGEN_OPT_CONTAINER_PATH")


def default_profiles_path() -> Path:
    roots = []
    if os.environ.get("DLPGEN_OPT_ROOT"):
        roots.append(Path(os.environ["DLPGEN_OPT_ROOT"]))
    roots.extend((Path(__file__).resolve().parents[2], Path.cwd()))
    for root in roots:
        candidate = root / "configs" / "slurm" / "s3df.yaml"
        if candidate.is_file():
            return candidate
    return roots[0] / "configs" / "slurm" / "s3df.yaml"
