schema_version: 1

production:
  name: bnb_icarus_v001
  output_dir: ../runs/bnb_icarus_v001
  jobs: 2
  generator_calls_per_job: 10
  base_seed: 104739
  seed_stride: 10

source:
  type: genie
  config: genie/bnb_icarus.yaml
  executable: dlpgen-opt-genie
  expected_commit: 4a6d9e5e50ed9ae72636dd363a2f3fbf672330a6
  dk2nu_expected_commit: 5b1d8c2cb72b5752a82592ea66af61d8e64a8343

software:
  container_image: dlpgen-opt:0.1.5
  edep_sim:
    executable: edep-sim
    expected_commit: 4548701be5bd82daae65c9f1e51f63b1886b71d9
  edep2supera:
    executable: dlpgen-opt-supera
    expected_commit: aabb3c717d8ca17fca3bf35a2ddb375193e0d943
  supera_atomic:
    expected_commit: 426408371d0a4bb20495cffabc0a8539df6fdae4

detector:
  geometry: geometry/lar_vat.gdml
  supera_config: supera/lar_sbn.yaml
  physics_list: QGSP_BERT

execution:
  resume: true
